-- Active: 1708264968229@@127.0.0.1@5433@postgres
CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(300) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(300) NOT NULL,
  "description" text,
  "may_have_tasks" bool,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_has_roles" (
  "user_id" integer NOT NULL,
  "role_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "schema_version" (
  "version" varchar(20),
  "dirty" boolean DEFAULT false
);

COMMENT ON COLUMN "roles"."may_have_tasks" IS 'Tasks can be assigned to this role if the value is true';

ALTER TABLE "user_has_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_has_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
