CREATE TABLE "accounts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "current_amount" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "reasons" (
  "id" integer PRIMARY KEY,
  "title" varchar(200) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "account_per_operation_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" integer NOT NULL,
  "amount" integer NOT NULL,
  "reason_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "account_per_day_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" integer NOT NULL,
  "amount" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "schema_version" (
  "version" varchar(20),
  "dirty" boolean DEFAULT false
);

COMMENT ON COLUMN "accounts"."current_amount" IS 'Current money amount.';

COMMENT ON COLUMN "account_per_operation_history"."amount" IS 'Amount of money added or subtracted.';

ALTER TABLE "account_per_operation_history" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "account_per_operation_history" ADD FOREIGN KEY ("reason_id") REFERENCES "reasons" ("id");

ALTER TABLE "account_per_day_history" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");
