CREATE TABLE "mq_offset" (
  "offset" integer NOT NULL,
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "failed_messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topic" varchar(300) NOT NULL,
  "group_id" varchar(300) NOT NULL,
  "message" bytea NOT NULL,
  "received_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" integer NOT NULL,
  "public_id" uuid UNIQUE NOT NULL,
  "email" varchar(300) NOT NULL,
  "username" varchar(300) NOT NULL,
  "first_name" varchar(300) NOT NULL,
  "last_name" varchar(300) NOT NULL,
  "enabled" bool NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "schema_version" (
  "version" varchar(20),
  "dirty" boolean DEFAULT false
);
